doc update

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -6,3 +6,9 @@ jobs:
     steps:
       - checkout
       - run: docker-compose down -v && docker-compose up --build && command bin/exec.sh
+      - command:  STATUS=$?
+        if [ $STATUS == 0 ]; then
+          echo "Command '$@' completed successfully"
+            else
+          echo "Command '$@' exited with error status $STATUS"
+        fi
